export const SEND_DATA = 'SEND_DATA'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USR_DATA = 'FETCH_USR_DATA'
export const FETCH_USR_TXS = 'FETCH_USR_TXS'
export const GET_USR_TXS = 'GET_USR_TXS'
export const NEW_TX = 'NEW_TX'

export const FETCH_IN_PENDING_TXS = 'FETCH_IN_PENDING_TXS'
export const FETCH_IN_APPROVED_TXS = 'FETCH_IN_APPROVED_TXS'
export const FETCH_OUT_PENDING_TXS = 'FETCH_OUT_PENDING_TXS'
export const FETCH_OUT_APPROVED_TXS = 'FETCH_OUT_APPROVED_TXS'

export const ACCEPT_TX = 'ACCEPT_TX'
export const REJECT_TX = 'REJECT_TX'

export const FETCH_POSSIBLE_USERS = 'FETCH_POSSIBLE_USERS'
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA'
export const DEC_DATA = 'DEC_DATA'
